baseURL = "http://podcast.tourcoder.com" # Your domain
title = "代码旅行" # Your podcast title
copyright = "tourcoder.com" # Your copyright information
theme = "hugocast" # Do nothing
disableKinds = ["sitemap"] # Do nothing
publishDir = "docs"

[params]
  defaultContentLanguage = "en-US" # Your podcast default language
  startyear = "2020" # Start year
  author = "Bin Hua" # Your name
  email = "code@tourcoder.com" # Your email address
  description = "Do Faith No Fear | 信仰永恒，无所畏惧 :)" # Your podcast description
  explicit = true # True or false
  podcastlogo = "podcastlogo.png" # Your podcast logo
  itunecategory = ["Comedy","Technology","Arts"] # Your podcast category, check the category, https://podcasts.apple.com/us/genre/podcasts/id26

[taxonomies]
  tag = "" # Do nothing
  group = "" # Do nothing
  category = "" # Do nothing